### ISSUE TITLE
Support data-uri image replacement in CSS 

### ISSUE THREAD

**Issue by redonkulus** [YahooArchive/mojito-shaker#10]
Using data-uri's inside CSS files for background-images can save unwanted HTTP requests and the need for extensive spriting. Allowing an option for Shaker to automatically convert images to data-uri's would be useful.

**Comment by diervo** [comment]
We will work on the image optimization hard soon, but is not a first class issue right now, I will enhance some stuff but for the full image support it will take a while ;)

**Comment by rwaldura** [comment]
Another request for this feature from the Y! Sports team.

> Inline background images in CSS files. This increased the load size from 85K (css + 4 images) to 315K (but a single CSS file)

**Comment by diervo** [comment]
@rwaldura Other teams so far are doing the css embded precompiler before shaker. Im working in the inline feature. Give this sprint ;)

**Comment by diervo** [comment]
Ok maybe a bit more ;)
