### ISSUE TITLE
App-level ac addons not included in compiled JS

### ISSUE THREAD

**Issue by kfay** [YahooArchive/mojito-shaker#11]
It appears that app level action context addons are not being included in any of the compiled js files.

folder structure:

frontend
    addons
        ac
            foo.common.js
    mojits
        MojitA
            MojitA.common.js

Where foo.common.js has a YUI module name of 'foo-addon' and MojitA.common.js declares it in its requires array.  It appears that foo.common.js is not in MojitA's compiled js file.

**Comment by diervo** [comment]
Looking...

**Comment by diervo** [comment]
Fixed (forgot the number track on the bug):
https://github.com/yahoo/mojito-shaker/commit/e2dfe35d8d0df7a5252b4a71eb45c598e48d8e4e#commitcomment-1530893
