### ISSUE TITLE
Device-specific view templates causing a JS error

### ISSUE THREAD

**Issue by kfay** [YahooArchive/mojito-shaker#12]
Given this folder structure:

frontend
    mojits
        MyMojit
            views
                index.desktop.mu.html
                index.mu.html

When I use compiled JS, the desktop template causes a JavaScript error :
Uncaught TypeError: Cannot set property 'desktop' of undefined

**Comment by diervo** [comment]
Im digging into the mojito code, and basically when you do mojito compile views having index.foo.html and index. Doesnt work at all, only picks one view.
So whats happening is that Shaker does this to embded the view in the JS:

YUI._mojito._cache.compiled.MyMojit.views.index.desktop = {// index.desktop content view};
YUI._mojito._cache.compiled.MyMojit.views.index = {// index content view};

So basically is a problem with the order. 
But more than that, I think is a problem with Mojito, which has this weird way to include views.
I will ask tomorrow Drew or Isao if they have anything in mind to fix this, if not I will create a pull request for them.

**Comment by diervo** [comment]
@drewfish @isao guys could you take a look at this, and tell if there is a another way to include (prefetch) views within  a JS other than the one we have legacy of "mojito compile" (YUI._mojito._cache.compiler.MyMojit...)?
