### ISSUE TITLE
Shaker won't do exclusions at the mojit level

### ISSUE THREAD

**Issue by rwaldura** [YahooArchive/mojito-shaker#25]
"Missing feature" according to customer feedback. I don't know much more than that.
@dferreiroval do you know what this means?

**Comment by diervo** [comment]
Um I guess we would like to exclude some files for some particular dimensions. But this can be done at mojit level with a shaker.json file
something like this would work for example:
dimensions:{
common: {},
region:{
   us: { exclude: ['path relative to the mojit assets.css']}
}
}

**Comment by rwaldura** [comment]
OK, well let's see if we can get some clarifications
@christopherbalz could you help?

**Comment by nottoseethesun** [comment]
We tried a mojit-level device-type exclusion as suggested above (only device-type, not region), but it did not work.  Iirc, the same thing did work fine for us at the application-level.  If a test case is needed, I can try to supply one for that.

**Comment by diervo** [comment]
I think that should work, but anyway, with the new shaker will be more simple. I will release it this week or next week! :)
