### ISSUE TITLE
Error when there are resource bundle for languages in mojits.

### ISSUE THREAD

**Issue by ghost** [YahooArchive/mojito-shaker#36]
I'm trying mojito@0.5.2 and mojito-shaker@3.0.0pr3. I run `mojito-shake` then `./node-start ./index.js' to compile assets and start node server. I meet with this error when access one of my page: 

GET http://l.yimg.com/zz/combo?tr/static/yui/yui-base/yui-base-min.js_e15871.js…-min.js_aafbdb.js&/static/loader-app.js&tr/loader-app-base_en-US_03e5bc.js 400 (Bad Request) footsafety.peking.corp.yahoo.com:24
Uncaught ReferenceError: YUI is not defined 

The problem is that /static/loader-app.js doesn't exist. The error disappears when I remove all language resource bundles (files under mojits/[mojit_name]/lang/). After I manually add the line 
&nbsp;&nbsp;"/static/loader-app.js": "tr/loader-app_e820f5.js", 
to "cdnModules" section of shaker-meta.json, the issue also resolves. 

Here is my source code:
https://git.corp.yahoo.com/yiwu/mobile-answers/tree/shake/apps/html5/trunk

**Comment by diervo** [comment]
Thanks @yiwu for the research and the explanation. The question to me is why /static/loader-app is not in cdnModules where it should be? I will take a look tomorrow using your app. I will keep you posted.

**Comment by diervo** [comment]
@yiwu I tryed your application, and I think it was an issue with having the shaker-meta already there with some content. I just puvlish a new pr5 version with a possible fix may help you. For me your app build and run perfectly fine.
Let me know...

**Comment by ghost** [comment]
Just tried and it works. Thanks so much!
