### ISSUE TITLE
Support font-face cdn pushes

### ISSUE THREAD

**Issue by redonkulus** [YahooArchive/mojito-shaker#9]
@font-face allows developers to specify custom font libraries in our CSS. Would be good if Shaker could push these file types to CDN automatically by parsing the file.

Types: .eot, .svg, .ttf, .woff

**Comment by diervo** [comment]
This week we will try to get support for this

**Comment by rwaldura** [comment]
this issue is getting closed because the feature has been implemented?

**Comment by diervo** [comment]
@rwaldura It is not, I was removing old open issues, this one should not be closed yet xD reopening

**Comment by aljimenez** [comment]
The latest shaker, processes and uploads all assets including images and web fonts. It also automatically updates url references in css files to correspond the the cdn urls of uploaded assets.
